name: Build and Deploy to AKS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: practicum15acr.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t practicum15acr.azurecr.io/arithmetic-service:${{ github.sha }} .
          docker push practicum15acr.azurecr.io/arithmetic-service:${{ github.sha }}
          docker tag practicum15acr.azurecr.io/arithmetic-service:${{ github.sha }} practicum15acr.azurecr.io/arithmetic-service:latest
          docker push practicum15acr.azurecr.io/arithmetic-service:latest
